# Generated by Django 4.1.1 on 2022-10-02 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                ("numReviews", models.IntegerField(blank=True, default=0, null=True)),
                ("description", models.TextField()),
                ("prep_time", models.IntegerField()),
                ("cook_time", models.IntegerField()),
                (
                    "food_type",
                    models.CharField(
                        choices=[
                            ("Vegetarian", "Vegetarian"),
                            ("Non Vegetarian", "Non Vegetarian"),
                        ],
                        default="Vegetarian",
                        max_length=100,
                    ),
                ),
                (
                    "cuisine_type",
                    models.CharField(
                        choices=[
                            ("Chinese", "Chinese"),
                            ("Indian", "Indian"),
                            ("Mexican", "Mexican"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=100,
                    ),
                ),
                ("main_photo", models.ImageField(upload_to="listings/")),
                ("photo_1", models.ImageField(upload_to="listings/")),
                ("photo_2", models.ImageField(upload_to="listings/")),
                ("photo_3", models.ImageField(upload_to="listings/")),
                ("is_published", models.BooleanField(default=False)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "contributor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
