# Generated by Django 4.1.1 on 2022-10-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="main_photo",
            field=models.ImageField(blank=True, null=True, upload_to="listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_1",
            field=models.ImageField(blank=True, null=True, upload_to="listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_2",
            field=models.ImageField(blank=True, null=True, upload_to="listings/"),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo_3",
            field=models.ImageField(blank=True, null=True, upload_to="listings/"),
        ),
    ]
