# Generated by Django 4.1.2 on 2022-10-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='meal_type',
            field=models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('SNACK', 'Snack'), ('DRINK', 'Drink')], default='LUNCH', max_length=100),
        ),
    ]
