# Generated by Django 4.1.2 on 2022-10-12 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_listing_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='cook_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='cuisine_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='prep_time',
        ),
    ]
