# Generated by Django 4.1.2 on 2022-10-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_remove_listing_cook_time_remove_listing_cuisine_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='qty',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
