# Generated by Django 4.1.2 on 2022-10-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_alter_ingredient_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPriceContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient')),
            ],
        ),
    ]
